# Generated by Django 4.1.7 on 2023-06-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ім'я", max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(help_text='Електронна пошта', max_length=254, verbose_name='Електронна пошта')),
                ('message', models.TextField(help_text='Повідомлення', verbose_name='Повідомлення')),
            ],
            options={
                'verbose_name_plural': 'Відгуки',
            },
        ),
    ]
