# Generated by Django 4.1.7 on 2023-07-01 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(help_text='Електронна пошта', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(help_text='Повідомлення (максимум 500 символів)', validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(500)], verbose_name='Повідомлення'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text="Ім'я", max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name="Ім'я"),
        ),
    ]
