# Generated by Django 4.1.7 on 2023-06-30 23:54

import app.services.generate_slug
import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import event.models.event
import event.models.gallery


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Назва події')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=app.services.generate_slug.generate_slug, unique=True)),
                ('description', models.TextField(blank=True, help_text='Опис події', null=True)),
                ('image', models.ImageField(blank=True, help_text='Логотип події (jpg, jpeg, png)', null=True, upload_to=event.models.event.upload_to_event_image, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Логотип події')),
                ('poster', models.ImageField(blank=True, help_text='Постер події (jpg, jpeg, png)', null=True, upload_to=event.models.event.upload_to_event_poster, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Постер події')),
                ('is_show', models.BooleanField(blank=True, default=True, help_text='Чи показувати подію', null=True)),
                ('archive', models.BooleanField(blank=True, default=False, help_text='Додати в архів', null=True)),
                ('charity', models.BooleanField(blank=True, default=False, help_text='Відмітка про благодійність', null=True)),
                ('start_time', models.DateTimeField(blank=True, help_text='Час початку події', null=True)),
                ('price', models.IntegerField(blank=True, help_text='Ціна події (від 0 до 9999), якщо вхід вільний залишити пусте поле', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('location', models.CharField(blank=True, help_text='Місце проведення події', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='Арт-простір “Ліхтар”', help_text='Адреса проведення події', max_length=255, null=True)),
                ('location_iframe', models.CharField(blank=True, help_text='Посилання на Google Maps < iframe src="https:...', max_length=500, null=True)),
                ('genre', models.CharField(blank=True, help_text='Жанр події', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Події',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Фото (jpg, jpeg, png)', upload_to=event.models.gallery.upload_to_gallery_image, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Фото')),
                ('youtube_url', models.URLField(blank=True, help_text='Посилання на відео на YouTube', null=True)),
                ('event', models.ForeignKey(help_text='Подія', on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='event.event')),
            ],
            options={
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, help_text='Відмітка про прибуття', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='event.event')),
                ('unregistered_user', models.ForeignKey(blank=True, help_text='Користувач, який не зареєстрований', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.unregistereduser')),
                ('user', models.ForeignKey(blank=True, help_text='Зареєстрований користувач', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Бронювання',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
