# Generated by Django 4.1.7 on 2023-07-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='performers',
            field=models.ManyToManyField(blank=True, help_text='Учасники події', related_name='events', to='performer.performer'),
        ),
    ]
