# Generated by Django 4.1.7 on 2023-07-01 01:20

import django.core.validators
from django.db import migrations, models
import event.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_performers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Галерея заходу'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='archive',
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, default='Арт-простір “Ліхтар”', help_text='Місце проведення події', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(help_text='Логотип події (jpg, jpeg, png)', null=True, upload_to=event.models.event.upload_to_event_image, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Логотип події'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Адреса проведення події', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(help_text='Час початку події', null=True),
        ),
    ]
