# Generated by Django 4.1.7 on 2023-06-30 23:54

import app.services.generate_slug
import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import performer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=app.services.generate_slug.generate_slug, unique=True)),
                ('logo', models.ImageField(help_text='Зображення виконавця', upload_to=performer.models.upload_performer_image, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('poster', models.ImageField(blank=True, help_text='Постер виконавця', null=True, upload_to=performer.models.upload_performer_poster, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('description', models.TextField(blank=True, help_text='Опис виконавця', null=True)),
                ('bank_to_support', models.URLField(blank=True, help_text='Посилання на підтримку виконавця')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.URLField(blank=True, help_text='Посилання на веб-сайт виконавця')),
                ('telegram', models.URLField(blank=True, help_text='Посилання на Telegram', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Посилання на Instagram', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Посилання на YouTube', null=True)),
                ('tiktok', models.URLField(blank=True, help_text='Посилання на TikTok', null=True)),
            ],
            options={
                'verbose_name_plural': 'Артист/колектив',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(help_text='Посилання на відео YouTube')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='performer.performer')),
            ],
            options={
                'verbose_name_plural': 'Посилання на YouTube',
            },
        ),
        migrations.CreateModel(
            name='PerformerGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Фото', upload_to='performer/photos', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='performer.performer')),
            ],
            options={
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(help_text='Фото учасника', upload_to=performer.models.upload_participant_photo, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='performer.performer')),
            ],
            options={
                'verbose_name_plural': 'Учасники',
            },
        ),
    ]
