# Generated by Django 4.1.7 on 2023-07-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name_plural': 'Учасники колективу'},
        ),
        migrations.AlterModelOptions(
            name='performergallery',
            options={'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'Відео на YouTube'},
        ),
    ]
